#version: '3.7'

services:

  # ------------------------------------------------------
  # nextcloud
  # ------------------------------------------------------

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    #hostname: nextcloud-app
    restart: unless-stopped
    depends_on:
      #- traefik
      - nextcloud-db
      - nextcloud-redis
    env_file:
      - .env
    environment:
      #MYSQL_HOST: nextcloud-db
      #MYSQL_DB: "${MYSQL_DB}"
      #MYSQL_USER: "${MYSQL_USER}"
      #MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: "${REDIS_HOST_PASSWORD}"
      TRUSTED_PROXIES: 10.0.1.0/24
      #VIRTUAL_HOST: "${BASE_URL}"
    networks:
      - overlay
      - default
    #ports:
    #  - "80:80"
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./config/custom.config.php:/opt/custom.config.php:ro
      - ./scripts/bootstrap-nextcloud-custom-config.sh:/docker-entrypoint-hooks.d/before-starting/bootstrap-nextcloud-custom-config.sh:ro
      - ./scripts/enable-and-configure-ldap.sh:/opt/enable-and-configure-ldap.sh

  # ------------------------------------------------------
  # mariadb / mysql
  # ------------------------------------------------------

  #nextcloud-db:
  #  image: mariadb:latest
  #  container_name: nextcloud-db
  #  hostname: nextcloud-db
  #  command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
  #  restart: unless-stopped
  #  environment:
  #    MYSQL_DB: "${MYSQL_DB}"
  #    MYSQL_USER: "${MYSQL_USER}"
  #    MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  #    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  #  networks:
  #    - default
  #  volumes:
  #    - ./data/mysql:/var/lib/mysql

  # ------------------------------------------------------
  # postgres
  # ------------------------------------------------------

  nextcloud-db:
    image: postgres:latest
    container_name: nextcloud-db
    #hostname: nextcloud-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
     - default
    volumes:
     - ./data/postgresql:/var/lib/postgresql/data

  # ------------------------------------------------------
  # redis
  # ------------------------------------------------------

  nextcloud-redis:
    image: redis:latest
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    environment:
      REDIS_HOST_PASSWORD: "${REDIS_HOST_PASSWORD}"
    command: redis-server --requirepass "${REDIS_HOST_PASSWORD}"
    networks:
      - default

# ------------------------------------------------------
# networks
# ------------------------------------------------------

networks:
  default:
    name: nextcloud
    driver: bridge
    #external: true
  overlay:
    name: overlay
    driver: overlay
    external: true

# ------------------------------------------------------
# volumes (example)
# ------------------------------------------------------

#volumes:
#  nextcloud_data:
#    driver: local
